routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('updatebrowser', function() {
    return view('canelatools::updateBrowser');
})->name('updatebrowser');

app/Models/BasicModel.php
<?php

namespace Canela\CanelaTools\Models;


use Canela\CanelaTools\Contracts\DeletableContract;
use Canela\CanelaTools\Manager\TranslationManager;
use Canela\CanelaTools\Traits\Deletable;
use Canela\CanelaTools\Traits\EloquentModelBread;
use Carbon\Carbon;
use Collective\Html\Eloquent\FormAccessible;
use Eloquent;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Lang;

/**
 * App\Models\Base\ModelApp
 *
 * @property-read mixed                             $created_at_format
 * @property-read mixed                             $updated_at_format
 * @property-read mixed                             $value_identificator
 * @property-read mixed                             $combo_identificator
 * @property-read mixed                             $created_at_short
 * @property-read mixed                             $updated_at_short
 * @property-read \Canela\CanelaTools\Models\Entity $table
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel comboList()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel comboListFilterId($id)
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel combolistFilter()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel query()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel comboBoolean()
 * @method static \Illuminate\Database\Eloquent\Builder|\Canela\CanelaTools\Models\BasicModel comboTranslate($filters = array())
 * @mixin Eloquent
 */
class BasicModel extends Eloquent implements DeletableContract
{
    use FormAccessible, EloquentModelBread, Deletable;

    const TYPE_CHANGE_STATE      = 1;
    const TYPE_CHANGE_USER_STATE = 2;

    public $tableIdentifierField = 'name';
    public $comboIdentifierField = 'name';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];


    /** @var string $routePath Model route path */
    protected static string $routePath = '';


    /** @var string $resourceTransPath Model resource translations path */
    protected static string $resourceTransPath = '';


    /**
     * @param string|null $path
     * @return string
     */
    public static function getRoutePath(?string $path = ''): string
    {
        return static::$routePath.$path;
    }


    /**
     * @param string|null $path
     * @return string
     */
    public static function getResourceTransPath(?string $path = ''): string
    {
        return static::$resourceTransPath.$path;
    }


    /**
     * @param string $path
     * @return string
     */
    public static function getResourceTrans(string $path): string
    {
        return trans(static::$resourceTransPath.$path);
    }


    /**
     * @param string $field
     * @return string
     */
    public static function getResourceFieldTrans(string $field): string
    {
        return static::getResourceTrans('field.'.$field);
    }


    /**
     * Returns table name.
     *
     * @return string
     */
    public static function getTableName(): string
    {
        return with(new static)->table;
    }

    /**
     * Get entity related model.
     *
     * @return Entity|null
     */
    public function entityModel()
    {
        return Entity::whereReference(self::getTableName())->first();
    }

    /**
     * Get entity related model (static).
     *
     * @return Entity|null
     */
    public static function entityModelStatic()
    {
        return Entity::whereReference(self::getTableName())->first();
    }


    /**
     * Formatea un numero.
     *
     * @param float  $number        Numero
     * @param int    $decimals      Numero de decimales
     * @param string $dec_sep       Separador de decimales
     * @param string $thousands_sep Separado de miles
     * @return string
     */
    public static function getNumberFormat($number, $decimals = 2, $dec_sep = ',', $thousands_sep = '.')
    {
        if (empty($number)) {
            return null;
        }

        return number_format($number, $decimals, $dec_sep, $thousands_sep);
    }

    /**
     * Returns table row identifier name.
     *
     * @return string
     */
    public function getValueIdentificatorAttribute()
    {
        return $this->getValueIdentifierAttribute();
    }

    /**
     * Returns table row identifier name.
     *
     * @return string
     */
    public function getValueIdentifierAttribute()
    {
        $attribute = $this->tableIdentifierField;
        $valor     = $this->$attribute;
        return (empty($valor) ? $this->id : $valor);
    }

    /**
     * return combo identifier attribute.
     *
     * @return mixed
     */
    public function getComboIdentificatorAttribute()
    {
        $attribute = $this->comboIdentifierField;
        return $this->$attribute;
    }

    /**
     * return combo identifier attribute.
     *
     * @return mixed
     */
    public function getComboIdentifierAttribute()
    {
        $attribute = $this->comboIdentifierField;
        return $this->$attribute;
    }

    /**
     * @return \Canela\CanelaTools\Models\Entity
     */
    public function getTableAttribute()
    {
        return Entity::getEntityByName($this->getTable());
    }

    /**
     * Get translated atribute.
     *
     * @param string $attribute
     * @param string|null $lang
     * @param string|null $default
     * @param bool $returnNullWhenNotFound
     * @return string|null
     */
    public function translate(string $attribute, ?string $lang = null, ?string $default = null, bool $returnNullWhenNotFound = false): ?string
    {
        return TranslationManager::translate($this, $this->getTable(), $attribute, $default ?? $this->$attribute ?? '', $this->id, $lang, $returnNullWhenNotFound);
    }

    /**
     * Normal combo.
     *
     * @param Builder $query
     * @return mixed
     */
    public function scopeComboList($query)
    {
        return $query->get()->pluck($this->getNameFieldComboBoxAttribute(), 'id');
    }


    /**
     * @param mixed $list
     * @return false|string
     */
    public static function getComboListJson($list)
    {
        $tmp = [];
        $list->each(function ($item, $key) use (&$tmp) {
            $tmp[] = [$key => $item];
        });
        return json_encode($tmp);
    }


    /**
     * Translated combo.
     * @param Builder $query
     * @param array   $filters Lista con los filtros a ejecutar. Se ha de poner la sentencia completa (campo = valor)
     * @return mixed
     */
    public function scopeComboTranslate($query, $filters = [])
    {
        // tiene filtros
        if (!empty($filters)) {
            foreach ($filters as $filter) {
                $query->whereRaw($filter);
            }
        }

        $attr = $this->getNameFieldComboBoxAttribute();
        return $query->get()->each(function (BasicModel $model) use ($attr) {
            $model->idtTranslateField = $model->translate($attr);
        })->pluck('idtTranslateField', 'id');
    }


    /**
     * @param Builder $query
     * @return mixed
     */
    public function scopeComboBoolean($query)
    {
        return collect(array(1 => trans('canelatools::canelatools.bool.yes'), 0 => trans('canelatools::canelatools.bool.no')));
    }


    /**
     * Combo for range.
     *
     * @param Builder $query
     * @param int     $start
     * @param int     $end
     * @param int     $step
     * @return \Illuminate\Support\Collection
     */
    public static function scopeComboRange($query, $start = 0, $end = 60, $step = 10)
    {
        return collect(range($start, $end, $step))->mapWithKeys(function ($value) use ($step) {
            return [($value - 1) => "{$value} - " . ($value + --$step)];
        });
    }


    /**
     * Converts boolean to text
     *
     * @param boolean $value
     *
     * @return string
     */
    public function booleanToText($value)
    {
        return self::booleanToTextStatic($value);
    }
    public static function booleanToTextStatic($value)
    {
        return ($value == 1 ? trans('canelatools::canelatools.bool.yes') : trans('canelatools::canelatools.bool.no'));
    }



    /**
     * Combo search except $filters
     *
     * @param Builder $query
     * @param Array $filters
     * @return mixed
     */
    public function scopeCombolistFilter($query, $filters = [])
    {
        // has filters?
        if (!empty($filters)) {
            foreach ($filters as $filter) {
                $query->whereRaw($filter);
            }
        }

        return $query->get()
                     ->pluck($this->getNameFieldComboBoxAttribute(), 'id');
    }



    /**
     * Combo search except provided ID
     * @param Builder $query
     * @param integer $id
     * @return mixed
     */
    public function scopeComboListFilterId($query, $id)
    {
        return $query->where('id', '<>', $id)
                     ->orderBy($this->getNameFieldComboBoxAttribute())
                     ->get()
                     ->pluck($this->getNameFieldComboBoxAttribute(), 'id');
    }

    /**
     * Establece el nombre de la columna que se usa en los ComboBox
     * @return string
     */
    protected function getNameFieldComboBoxAttribute()
    {
        return $this->comboIdentifierField;
    }

    /**
     * Formato para fecha Larga.
     *
     * @param string $fecha

resources/views/rest/layouts/addEdit-breadcrumbs.blade.php
<div class="page-header-title">
    <h5 class="m-b-10">{{ trans((empty($register) ? "canelatools::canelatools.canela-rest.form.title.new" : "canelatools::canelatools.canela-rest.form.title.edit"), ['model' => $tableRest->formTitle ?? $title]) }}</h5>
</div>
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url('dashboard') }}"><i class="feather icon-home"></i></a></li>
    <li class="breadcrumb-item"><a href="{{ $tableRest->urlIndex }}">{{ $title }}</a></li>
    @if(!empty($register))
        <li class="breadcrumb-item"><a href="#">{{ $register->value_identifier }}</a></li>
    @endif
</ul>

resources/views/rest/layouts/associated-horaries.blade.php
@section('associated-horaries-nav-item')
    <li class="nav-item">
        <a class="nav-link text-uppercase has-ripple" id="associated-horaries-tab" data-toggle="tab" href="#associated-horaries"
            role="tab" aria-controls="associated-horaries" aria-selected="false">@lang('canelatools::canelatools.canela-rest.form.label.associated-horaries')<span class="ripple ripple-animate"></span></a>
    </li>
@endsection

@section('associated-horaries-tab-content')
    <div class="tab-pane p-t-10 fade" id="associated-horaries" role="tabpanel" aria-labelledby="associated-horaries-tab">
        <div class="m-b-20">

            <div class="m-b-20">
                <div class="btn-group">
                    <a class="btn btn-success btn-tumblr waves-effect waves-light"
                       href="{{ $webPageNoticeHoraryTableRest?->urlAdd.'?notice_id='.$register->id }}">
                        <i class="fa fa-plus"></i> {{ trans('canelatools::canelatools.canela-rest.list.btn.new',
                        ['model' => $webPageNoticeHoraryTableRest?->formTitle]) }}</a>
                </div>
            </div>

            @include('canelatools::rest.layouts.table', array('tableRest' => $webPageNoticeHoraryTableRest))

        </div>
    </div>
@endsection

@section('body-scripts')
    @parent

    <script type="text/javascript">

        jQuery(document).ready(function () {


        });
    </script>
@endsection

resources/views/rest/layouts/associated-sections.blade.php
@section('associated-sections-nav-item')
    <li class="nav-item">
        <a class="nav-link text-uppercase has-ripple" id="associated-sections-tab" data-toggle="tab" href="#associated-sections" role="tab" aria-controls="associated-sections" aria-selected="false">@lang('canelatools::canelatools.canela-rest.form.label.associated-sections')<span class="ripple ripple-animate"></span></a>
    </li>
@endsection

@section('associated-sections-tab-content')
    <div class="tab-pane p-t-10 fade" id="associated-sections" role="tabpanel" aria-labelledby="associated-sections-tab">
        <div class="m-b-20">
            <div class="row associated-items-list">
                @foreach($register->sections()->with('fileThumb')->get() as $item)
                    <div class="col-sm-12 col-md-6 col-lg-3 col-xl-2 associated-item-container" data-id="{{$item->id}}">
                        <div>
                            <div class="sortable-move-icon-header"><i class="fa fa-arrows-alt"></i></div>
                            <?php
                            /** @var \Canela\CanelaTools\Models\WebBuilder\WebPageSection $item */
                            $archive = $item->fileThumb;
                            $archiveName = $archive?->translate('archive');
                            $archiveUrl = asset(\Canela\CanelaTools\Models\General\Archive::DIR_ARCHIVES.$archiveName);
                            $sectionUrl = route('admin.webbuilder.webpagesection.edit', $item->id);
                            ?>
                            @if (!is_null($archive) && $archive->type_id == \Canela\CanelaTools\Models\General\ArchiveType::IMAGE)
                                <a href="{{$sectionUrl}}">
                                    <img src="{{$archiveUrl}}" alt="{{$archive->translate('title')}}">
                                </a>
                            @endif
                            <div class="item-name-container"><a href="{{$sectionUrl}}">{!! $item->translate('title') !!}</a></div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@section('body-scripts')
    @parent

    <script type="text/javascript">

        jQuery(document).ready(function () {

            const $associatedSectionsList = jQuery('#associated-sections .associated-items-list');

            jQuery.sortAssociatedSections = function () {
                const ids = $associatedSectionsList.find('.associated-item-container').map(function () {
                    return jQuery(this).data('id');
                }).toArray();

                jQuery.ajax({
                    url: '{{route($tableRest->routeEntity.'.ajax.sortassociatedsections', $register->id)}}',
                    dataType: "json",
                    data: {
                        '_token': '{{ csrf_token() }}',
                        '_method': 'PATCH',
                        'ids': ids
                    },
                    type: "POST",
                    processData: true,
                    beforeSend: function () {
                        jQuery.loadIni();
                    },
                    error: function (jqXHR, exception, errorThrown) {
                        const msg = jQuery.procesarRespuestaAjax(jqXHR, exception, errorThrown);
                        jQuery.messageWarning(msg);
                        jQuery.loadEnd();
                    },
                    success: function (data) {
                        if (data.result) {
                            jQuery.messageSuccess(data.message);
                        } else {
                            jQuery.messageWarning(data.message);
                        }
                        jQuery.loadEnd();
                    },
                });

            }

            $associatedSectionsList.sortable({
                update: function () {
                    jQuery.sortAssociatedSections();
                }
            });

        });
    </script>
@endsection

resources/views/rest/layouts/file-delete.blade.php
@section('body-scripts')
    @parent
    <script type="text/javascript">
        jQuery(document).ready(function () {

            /***** File Delete *****/
            @if(!empty($register))
                jQuery.confirmDeleteFile = function (fileId, fileName, type) {
                    Swal.fire({
                        text: (type === '{{\Canela\CanelaTools\Enums\TableColumnTypes::FILE}}') ? '{{trans('canelatools::canelatools.canela-rest.label.question_delete_file')}}' : '{{trans('canelatools::canelatools.canela-rest.label.question_delete_image')}}',
                        showCancelButton: true,
                        confirmButtonText: '{{trans('canelatools::canelatools.buttons.continue')}}',
                        cancelButtonText: '{{trans('canelatools::canelatools.buttons.cancel')}}',
                    }).then(function (result) {
                        if (result.isConfirmed) {
                            jQuery.deleteFile(fileId, fileName, type);
                        }
                    });
                }

                jQuery.deleteFile = function(fileId, fileName, dir, type) {
                    jQuery.loadIni();

                    const formdata = new FormData();
                    formdata.append('_token', '{{ csrf_token() }}');
                    formdata.append('id', {{$register->id}});
                    formdata.append('field_name', fileName);
                    formdata.append('dir', dir);

                    jQuery.ajax({
                        url: '{{$deleteFileUrl}}',
                        dataType: "json",
                        data: formdata,
                        type: "POST",
                        processData: false,
                        contentType: false,
                        beforeSend: function () {
                            jQuery.loadIni();
                        },
                        error: function (jqXHR, exception, errorThrown) {
                            var msg = jQuery.procesarRespuestaAjax(jqXHR, exception, errorThrown);
                            jQuery.messageWarning(msg);
                            jQuery.loadEnd();
                        },
                        success: function (data) {
                            if (data.result) {
                                const container = jQuery('#canela-input-file-container-'+fileId);
                                container.find('.preview-container img').prop('src', '');
                                container.find('a.file-link').remove();
                                container.find('a.remove-file-link').remove();

                                jQuery.messageInfo((type === '{{\Canela\CanelaTools\Enums\TableColumnTypes::FILE}}')
                                                    ? '{{trans('canelatools::canelatools.canela-rest.label.file_deleted_successfully')}}'
                                                    : '{{trans('canelatools::canelatools.canela-rest.label.image_deleted_successfully')}}');
                            } else {
                                jQuery.messageWarning(data.message);
                            }
                            jQuery.loadEnd();
                        },
                    });
                };
            @endif
            /***** /File Delete *****/

        });
    </script>
@endsection

resources/views/rest/layouts/file-input.blade.php
<?php
    /** @var string $type */
    /** @var string $fileId */
    /** @var string $fileName */
    /** @var string $fileDir */
    /** @var string $fileValue */

    use Canela\CanelaTools\Enums\TableColumnTypes;

    $tableColumnTypeClass = match($type) {
        TableColumnTypes::IMAGE => ' canela-input-image',
        TableColumnTypes::IMAGE_CROPPER => ' canela-input-image-cropper',
        default => '',
    };
?>
<div class="preview-container">
    @if (\Canela\CanelaTools\Enums\TableColumnTypes::isImageType($type))
        <img src="{{empty($register) ? '' : asset($fileDir.$fileValue)}}" alt="">
    @else
        @if(!empty($register) && !empty($fileValue))
            <a href="{{asset($fileDir.$fileValue)}}" class="file-link" target="_blank">{{$fileValue}}</a>
        @endif
    @endif

    @if(!empty($register) && !empty($fileValue))
        <a href="javascript:jQuery.confirmDeleteFile('{{$fileId}}', '{{$fileName}}', '{{$fileDir}}', '{{$type}}')" class="image-action-icon-link remove-file-link"><i class="fa fa-trash-alt"></i></a>
    @endif
    <a href="javascript:jQuery.cleanFile('{{$fileId}}', '{{$type}}')" class="image-action-icon-link clean-file-link" style="display: none;"><i class="fa fa-times"></i></a>
</div>
{!! Form::file($fileName, array('class' => 'form-control canela-input-text'.$tableColumnTypeClass, 'id' => $fileId)) !!}

resources/views/rest/layouts/file-preview.blade.php
@section('body-scripts')
    @parent
    <script type="text/javascript">
        @php
            $initialImages = empty($register) ? '{}' : collect($tableRest->tableForm)->filter(function ($tableForm) use ($register) {
                                            $field = $tableForm->name;
                                            $value = $register->$field;
                                            return \Canela\CanelaTools\Enums\TableColumnTypes::isImageType($tableForm->type) && !is_null($value);
                                        })->mapWithKeys(function ($tableForm) use ($register) {
                                            $id = $tableForm->id;
                                            $field = $tableForm->name;
                                            $value = asset($tableForm->getFileDir().$register->$field);
                                            return [$id => $value];
                                        })->toJson();
        @endphp

        var initialImages = JSON.parse('{!!$initialImages!!}');

        jQuery(document).ready(function () {

            jQuery('.canela-input-image').on('change', function (e) {
                const input = e.target;
                const files = input.files;
                const [file] = files;
                if (file) {
                    const canelaInputFileContainer = document.getElementById('canela-input-file-container-' + input.id);
                    canelaInputFileChangedContainer = jQuery(canelaInputFileContainer);
                    previewImage = jQuery(canelaInputFileContainer).find('.preview-container img').get(0);
                    previewImage.src = URL.createObjectURL(file);

                    canelaInputFileChangedContainer.find('a.remove-file-link').hide();
                    canelaInputFileChangedContainer.find('a.clean-file-link').show();
                }
            });

            jQuery.cleanFile = function (fileId, type) {
                const containerId = 'canela-input-file-container-' + fileId;
                const container = jQuery('#' + containerId);
                const imagePreview = container.find('.preview-container img');

                if (initialImages[fileId] !== undefined) {
                    imagePreview.prop('src', initialImages[fileId]);
                    container.find('a.remove-file-link').show();
                } else {
                    imagePreview.prop('src', '');
                }

                container.find('a.clean-file-link').hide();

                if (type === '{{\Canela\CanelaTools\Enums\TableColumnTypes::IMAGE_CROPPER}}') {
                    delete cropperImages[fileId];
                } else {
                    container.find('input').val(null);
                }
            };

        });
    </script>
@endsection

resources/views/rest/layouts/form-items-include.blade.php
@if(empty($register))
    {!! Form::open(['id' => 'modelForm', 'route' => $tableRest->urlStore, 'method' => 'POST', 'role' => 'form', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data']) !!}
@else
    @if(($tableRest->showBtnEdit ?? false))
        {!! Form::model($register, ['id' => 'modelForm', 'route' => [$tableRest->urlUpdate, $register], 'method' => 'PUT', 'role' => 'form', 'class' => 'form-horizontal']) !!}
    @endif
@endif

    <!-- Parametros ocultos -->
    @foreach($tableRest->getParametersHidden() as $key => $value)
        {!! Form::hidden($key, $value, array('id' => $key)) !!}
    @endforeach

    @include('canelatools::rest.layouts.form-items')

    <div class="col-12 card-block button-list text-center">
        @if(($tableRest->showBtnEdit ?? false))
            <a class="btn btn-primary" data-action="submit">@lang('canelatools::canelatools.canela-rest.form.btn.save')</a>
        @endif
        <a class="btn btn-secondary" type="button"
           href="{{ $redirectUrl }}">@lang('canelatools::canelatools.canela-rest.form.btn.cancel')</a>
    </div>


@if(empty($register) || ($tableRest->showBtnEdit ?? false))
    {!! Form::close() !!}
@endif

resources/views/rest/layouts/form.blade.php
<?php
/* @var Canela\CanelaTools\Models\Table\TableRest $tableRest */

    use Canela\CanelaTools\Models\WebBuilder\WebPage;
    use Canela\CanelaTools\Models\WebBuilder\WebPageNotice;

    $isWebPageNotice = !empty($register) && $register instanceof WebPageNotice;
    $withArchives = !empty($register) && method_exists($register, 'archives');
    $withSections = !empty($register) && $register instanceof WebPage && $register->type->with_section;

    /** @var String $nameSectionScript nombre de la seccion donde se añade el script*/
    $nameSectionScript = $nameSectionScript ?? config('canelatools.blade.section.bodyScriptsExtra');
?>

@includeWhen($isWebPageNotice, 'canelatools::rest.layouts.associated-horaries', ['webPageNoticeHoraryTableRest' => $webPageNoticeHoraryTableRest ?? null])
@includeWhen($withArchives, 'canelatools::rest.layouts.associated-archives')
@includeWhen($withSections, 'canelatools::rest.layouts.associated-sections')

@if ($isWebPageNotice || $withArchives || $withSections)
    <ul class="nav nav-tabs mb-3" id="editTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link text-uppercase has-ripple active" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true">@lang('canelatools::canelatools.canela-rest.form.label.general')<span class="ripple ripple-animate"></span></a>
        </li>
        @yield('associated-horaries-nav-item')
        @yield('associated-archives-nav-item')
        @yield('associated-sections-nav-item')
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane p-t-10 fade active show" id="general" role="tabpanel" aria-labelledby="general-tab">
            @include('canelatools::rest.layouts.form-items-include')
        </div>
        @yield('associated-horaries-tab-content')
        @yield('associated-archives-tab-content')
        @yield('associated-sections-tab-content')
    </div>
@else
    @include('canelatools::rest.layouts.form-items-include')
@endif

@section('global-scripts')
    @parent
    <script type="text/javascript">
        var classicEditors = {};
    </script>
@endsection


@section('body-scripts-extra')
    @parent

    <script type="text/javascript">

        jQuery(document).ready(function () {

            /******************************************************************************************
             * Control de numero de caracteres
             ******************************************************************************************/
            jQuery.updateCharacterText = function(object)
            {
                var str  = jQuery(object).val();
                var len  = str.length;
                var id = jQuery(object).attr('id');
                jQuery('span[data-id="'+id+'"].canela-input-text').html("&nbsp;("+len+")&nbsp;");
            }

            jQuery("input.canela-input-text, textarea.canela-input-text").keyup(function(){
                jQuery.updateCharacterText(this);
            })

            jQuery('input.canela-input-text, textarea.canela-input-text').each(function()
            {
                jQuery.updateCharacterText(this);
            });
            /******************************************************************************************
             * FIN - Control de numero de caracteres
             ******************************************************************************************/

        });
    </script>
@endsection

resources/views/rest/layouts/list-breadcrumbs.blade.php
<div class="page-header-title">
    <h5 class="m-b-10">{{ $title }}</h5>
</div>
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url('dashboard') }}"><i class="feather icon-home"></i></a></li>
    <li class="breadcrumb-item"><a href="#">{{ $title }}</a></li>
</ul>

resources/views/rest/layouts/select-input-scripts.blade.php
@section('body-modals')
    @parent

    <!-- Modal -->
    <div id="modal-select-input" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-full">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title h4">Large Modal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
    <!--end: Modal -->

@endsection

@section('body-scripts-extra')
    @parent

    <script type="text/javascript">
        jQuery(function () {
            jQuery('a.btn-select-input').on('click', function (e) {
                e.preventDefault();
                const btn = jQuery(e.currentTarget);
                switch(btn.data('type')) {
                    case 'select':
                        jQuery.selectItem(btn.data('name'));
                        break;
                    case 'clean':
                        jQuery.cleanInput(btn.data('name'));
                        break;
                    case 'add':
                        jQuery.addItem(btn.data('name'));
                        break;
                    case 'edit':
                        jQuery.editItem(btn.data('name'));
                }
            });

            jQuery.selectItem = function (name) {
                console.log(name);

                const modal = jQuery('#modal-select-input');

                $.get("{{route('admin.general.archive.ajax.list')}}",
                function (data) {
                    modal.find('.modal-content').html(data);
                    modal.modal('show')
                });
            };

            jQuery.cleanInput = function (name) {
                console.log(name);
            };

            jQuery.addItem = function (name) {
                console.log(name);
            };

            jQuery.editItem = function (name) {
                console.log(name);
            };
        });
    </script>
@endsection